num_rounds: 1_000
num_clients_per_round: 5
learning_rate: 0.001
epochs_per_round: 5
batches_per_round: null
same_train_test_clients: False

results_dir_path: "./results/table2_flwr_baseline_partial_FeMNIST"
