name: Deprecated-Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

defaults:
  run:
    working-directory: baselines/flwr_baselines

jobs:
  test_deprecated_baselines:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test.sh
