name: Framework

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test_core:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Latest version which comes cached in the host image can be found here:
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#python
        # In case of a mismatch, the job has to download Python to install it.
        # Note: Due to a bug in actions/setup-python we have to put 3.10 in
        # qoutes as it will otherwise will assume 3.1
        python: [3.7, 3.8, 3.9, '3.10']

    name: Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies (mandatory only)
        run: python -m poetry install --all-extras
      - name: Check if protos need recompilation
        run: ./dev/check-protos.sh
      - name: Lint + Test (isort/black/docformatter/mypy/pylint/flake8/pytest)
        run: ./dev/test.sh
